name: volta
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  anthropic_sdk_dart: ^0.0.1-dev.1
  context_menus: ^2.0.0+1
  file_picker: ^8.0.3
  fluent_ui: ^4.8.7
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  get_it: ^7.7.0
  markdown: ^7.2.2
  markdown_widget: ^2.3.2+6
  mockito: ^5.4.4
  path: ^1.9.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  re_highlight: ^0.0.3
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tools/
